services:
    Phpbb\SessionsAuthBundle\Subscriber\TablePrefixSubscriber:
        public: false
        arguments: ["%phpbb_sessions_auth.database.prefix%"]
        tags:
            - { name: doctrine.event_subscriber }

    Phpbb\SessionsAuthBundle\Security\PhpbbSessionAuthenticator:
        public: false
        arguments:
            - "%phpbb_sessions_auth.session.cookie_name%"
            - "%phpbb_sessions_auth.session.login_page%"
            - "%phpbb_sessions_auth.session.force_login%"
            - "@Phpbb\\SessionsAuthBundle\\Security\\PhpbbUserProvider"

    Phpbb\SessionsAuthBundle\Security\PhpbbUserProvider:
        public: false
        arguments: ["@doctrine", "%phpbb_sessions_auth.database.entity_manager%"]
        calls: [[setRoles, ["%phpbb_sessions_auth.roles%"]]]
